### PR TITLE
solve issue #233 - including port for 443 HTTPs

### PR DESCRIPTION
**Pull request by vrajjbhatt**
Link to issue
https://github.com/awslabs/aws-cloudformation-templates/issues/233

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by ami-spark — CHANGES_REQUESTED** [review]
All good!

**Comment by vrajjbhatt** [comment]
> All good!

Is it good to go for merging?

**Comment by vrajjbhatt** [comment]
> All good!

@ami-spark Are we good to go for merge?

**Comment by ami-spark** [comment]
Template access in API, sdk

मंगल, 23 अप्रै 2024, 02:42 को Eric Z. Beard ***@***.***> ने
लिखा:

**Pull request closed without merging**
